CT288Book/Controllers/BookController.cs
using CT288Book.Data;
using CT288Book.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace CT288Book.Controllers
{
    public class BookController : Controller
    {
        private readonly BookShopContext db;

        public BookController(BookShopContext context)
        {
            db = context;
        }
        public IActionResult Index(int? loai)
        {
            var books = db.Books.AsQueryable();
            if (loai.HasValue)
            {
                books = books.Where(p => p.MaLoai == loai.Value);
            }

            var result = books.Select(p => new BookVM
            {
                MaHh = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                TenLoai = p.MaLoaiNavigation.TenLoai

            });

            return View(result);
        }
        public IActionResult Search(string query)
        {
            var books = db.Books.AsQueryable();
            if (query != null)
            {
                books = books.Where(p => p.TenHh.Contains(query));
            }

            var result = books.Select(p => new BookVM
            {
                MaHh = p.MaHh,
                TenHH = p.TenHh,
                DonGia = p.DonGia ?? 0,
                Hinh = p.Hinh ?? "",
                MoTaNgan = p.MoTaDonVi ?? "",
                TenLoai = p.MaLoaiNavigation.TenLoai

            });

            return View(result);
        }
        public IActionResult Detail(int id)
        {
            var data = db.Books
                .Include(p => p.MaLoaiNavigation)
                .SingleOrDefault(p => p.MaHh == id);
            if (data == null)
            {
                TempData["Message"] = $"Không thấy sản phẩm có mã {id}";
                return Redirect("/404");
            }
            var result = new ChiTietBookVM
            {
                MaHh = data.MaHh,
                TenHH = data.TenHh,
                DonGia = data.DonGia ?? 0,
                ChiTiet = data.MoTa ?? string.Empty,
                Hinh = data.Hinh ?? string.Empty,
                MoTaNgan = data.MoTaDonVi ?? string.Empty,
                TenLoai = data.MaLoaiNavigation.TenLoai,
                SoLuongTon = 10,//tính sau
                DiemDanhGia = 5,//check sau
            };
            return View(result);
        }
    }
}

CT288Book/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CT288Book.Data;

namespace CT288Book.Controllers
{
    public class BooksController : Controller
    {
        private readonly BookShopContext _context;

        public BooksController(BookShopContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var bookShopContext = _context.Books.Include(b => b.MaLoaiNavigation).Include(b => b.MaNccNavigation);
            return View(await bookShopContext.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.MaLoaiNavigation)
                .Include(b => b.MaNccNavigation)
                .FirstOrDefaultAsync(m => m.MaHh == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai");
            ViewData["MaNcc"] = new SelectList(_context.NhaXbs, "MaNcc", "MaNcc");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHh,TenHh,TenAlias,MaLoai,MoTaDonVi,DonGia,Hinh,NgaySx,GiamGia,SoLanXem,MoTa,MaNcc")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai", book.MaLoai);
            ViewData["MaNcc"] = new SelectList(_context.NhaXbs, "MaNcc", "MaNcc", book.MaNcc);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai", book.MaLoai);
            ViewData["MaNcc"] = new SelectList(_context.NhaXbs, "MaNcc", "MaNcc", book.MaNcc);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHh,TenHh,TenAlias,MaLoai,MoTaDonVi,DonGia,Hinh,NgaySx,GiamGia,SoLanXem,MoTa,MaNcc")] Book book)
        {
            if (id != book.MaHh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.MaHh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai", book.MaLoai);
            ViewData["MaNcc"] = new SelectList(_context.NhaXbs, "MaNcc", "MaNcc", book.MaNcc);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.MaLoaiNavigation)
                .Include(b => b.MaNccNavigation)
                .FirstOrDefaultAsync(m => m.MaHh == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.MaHh == id);
        }
    }
}

CT288Book/Controllers/CartController.cs
using CT288Book.Data;
using CT288Book.ViewModels;
using Microsoft.AspNetCore.Mvc;
using CT288Book.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace CT288Book.Controllers
{
    public class CartController : Controller
    {
        private readonly BookShopContext db;

        public CartController(BookShopContext context) 
        {
            db = context;
        }
        public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(MySetting.CART_KEY) ?? new List<CartItem>();
        public IActionResult Index()
        {
            return View(Cart);
        }
        public IActionResult AddToCart(int id, int quantity = 1)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item == null)
            {
                var book = db.Books.SingleOrDefault(p => p.MaHh == id);
                if (book == null)
                {
                    TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
                    return Redirect("/404");
                }
                item = new CartItem
                {
                    MaHh = book.MaHh,
                    TenHH = book.TenHh,
                    DonGia = book.DonGia ?? 0,
                    Hinh = book.Hinh ?? string.Empty,
                    SoLuong = quantity
                };
                gioHang.Add(item);
            }
            else
            {
                item.SoLuong += quantity;
            }

            HttpContext.Session.Set(MySetting.CART_KEY, gioHang);

            return RedirectToAction("Index");
        }
        public IActionResult RemoveCart(int id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                gioHang.Remove(item);
                HttpContext.Session.Set(MySetting.CART_KEY, gioHang);
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        [HttpGet]
		public IActionResult Checkout() 
        {
            if(Cart.Count == 0)
            {
                return Redirect("/");
            }

            return View(Cart);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Checkout(CheckoutVM model)
        {
            if (ModelState.IsValid)
            {
            

                var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID).Value;
                var khachHang = new KhachHang();
                if (model.GiongKhachHang)
                {
                    khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerId);
                }

                var hoadon = new HoaDon
                {
                    MaKh = customerId,
                    HoTen = model.HoTen ?? khachHang.HoTen,
                    DiaChi = model.DiaChi ?? khachHang.DiaChi,
                    DienThoai = model.DienThoai ?? khachHang.DienThoai,
                    NgayDat = DateTime.Now,
                    CachThanhToan = "COD",
                    CachVanChuyen = "GRAB",
                    MaTrangThai = 0,
                    GhiChu = model.GhiChu
                };

                db.Database.BeginTransaction();
                try
                {

                    db.Add(hoadon);
                    db.SaveChanges();

                    var cthds = new List<ChiTietHd>();
                    foreach (var item in Cart)
                    {
                        cthds.Add(new ChiTietHd
                        {
                            MaHd = hoadon.MaHd,
                            SoLuong = item.SoLuong,
                            DonGia = item.DonGia,
                            MaHh = item.MaHh,
                            GiamGia = 0
                        });
                    }
                    db.AddRange(cthds);
                    db.SaveChanges();
                    db.Database.CommitTransaction();

                    HttpContext.Session.Set<List<CartItem>>(MySetting.CART_KEY, new List<CartItem>());

                    return View("Success");
                }
                catch
                {
                    db.Database.RollbackTransaction();
                }
            }

            return View(Cart);
        }
    }
}

CT288Book/ViewComponents/MenuLoaiViewComponent.cs
using CT288Book.Data;
using CT288Book.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CT288Book.ViewComponents
{
    public class MenuLoaiViewComponent : ViewComponent
    {
        private readonly BookShopContext db;

        public MenuLoaiViewComponent(BookShopContext context) => db = context;
        public IViewComponentResult Invoke()
        {
            var data = db.Loais.Select(lo => new MenuLoaiVM
            {
                MaLoai = lo.MaLoai,
                TenLoai = lo.TenLoai,
                SoLuong = lo.Books.Count
            }).OrderBy(p =>p.TenLoai);
            return View(data);
        }
    }
}

CT288Book/Views/Book/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
}
<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
	<h1 class="text-center text-white display-6">Shop Detail</h1>
	<ol class="breadcrumb justify-content-center mb-0">
		<li class="breadcrumb-item"><a href="#">Home</a></li>
		<li class="breadcrumb-item"><a href="#">Book</a></li>
		<li class="breadcrumb-item active text-white">@Model.TenHH</li>
	</ol>
</div>
<!-- Single Page Header End -->
<!-- Single Product Start -->
<div class="container-fluid py-5 mt-5">
	<div class="container py-5">
		<div class="row g-4 mb-5">
			<div class="col-lg-8 col-xl-9">
				<div class="row g-4">
					<div class="col-lg-6">
						<div class="border rounded">
							<a asp-action="Detail" asp-route-id="@Model.MaHh">
								<img src="~/Hinh/HangHoa/@Model.Hinh" class="img-fluid rounded" alt="@Model.TenHH">
							</a>
						</div>
					</div>
					<div class="col-lg-6">
						<h4 class="fw-bold mb-3">@Model.TenHH</h4>
						<p class="mb-3">Category: @Model.TenLoai</p>
						<h5 class="fw-bold mb-3">$ @Model.DonGia</h5>
						<div class="d-flex mb-4">
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star"></i>
						</div>
						<p class="mb-4">@Model.MoTaNgan</p>
						<form asp-action="AddToCart" asp-controller="Cart" asp-route-id="@Model.MaHh">
							<div class="input-group quantity mb-5" style="width: 100px;">
								<div class="input-group-btn">
									<button class="btn btn-sm btn-minus rounded-circle bg-light border" type="button">
										<i class="fa fa-minus"></i>
									</button>
								</div>
								<input type="text" class="form-control form-control-sm text-center border-0" value="1" name="quantity">
								<div class="input-group-btn">
									<button class="btn btn-sm btn-plus rounded-circle bg-light border" type="button">
										<i class="fa fa-plus"></i>
									</button>
								</div>
							</div>
							<button class="btn border border-secondary rounded-pill px-4 py-2 mb-4 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Mua hàng</button>
						</form>
					</div>
					<div class="col-lg-12">
						<nav>
							<div class="nav nav-tabs mb-3">
								<button class="nav-link active border-white border-bottom-0" type="button" role="tab"
										id="nav-about-tab" data-bs-toggle="tab" data-bs-target="#nav-about"
										aria-controls="nav-about" aria-selected="true">
									Thông tin book
								</button>
							
							</div>
						</nav>
						<div class="tab-content mb-5">
							<div class="tab-pane active" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
								@Model.ChiTiet
							</div>

						</div>
					</div>
					<form action="#">
						<h4 class="mb-5 fw-bold">Leave a Reply</h4>
						<div class="row g-4">
							<div class="col-lg-6">
								<div class="border-bottom rounded">
									<input type="text" class="form-control border-0 me-4" placeholder="Yur Name *">
								</div>
							</div>
							<div class="col-lg-6">
								<div class="border-bottom rounded">
									<input type="email" class="form-control border-0" placeholder="Your Email *">
								</div>
							</div>
							<div class="col-lg-12">
								<div class="border-bottom rounded my-4">
									<textarea name="" id="" class="form-control border-0" cols="30" rows="8" placeholder="Your Review *" spellcheck="false"></textarea>
								</div>
							</div>
							<div class="col-lg-12">
								<div class="d-flex justify-content-between py-3 mb-5">
									<div class="d-flex align-items-center">
										<p class="mb-0 me-3">Please rate:</p>
										<div class="d-flex align-items-center" style="font-size: 12px;">
											<i class="fa fa-star text-muted"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
										</div>
									</div>
									<a href="#" class="btn border border-secondary text-primary rounded-pill px-4 py-3"> Post Comment</a>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="col-lg-4 col-xl-3">
				<div class="row g-4 fruite">
					<div class="col-lg-12">
						@await Html.PartialAsync("_TimKiemPanel")
						@await Component.InvokeAsync("MenuLoai")
					</div>
				
				</div>
			</div>
		</div>
	</div>
</div>

CT288Book/Views/Book/Index.cshtml
@model IEnumerable<CT288Book.ViewModels.BookVM>
@{
    ViewData["Title"] = "Index";
    Layout = "_DanhSachBook";
}

<!-- Single Page Header start -->
@section BreadCum
{
    <div class=" py-5">
        <h1 class="text-center text-black display-6">Shop</h1>
    <ol class="breadcrumb justify-content-center mb-0">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Pages</a></li>
        <li class="breadcrumb-item active text-black">Shop</li>
    </ol>
</div>

}
<!-- Single Page Header End -->
@await Html.PartialAsync("ProductItem", Model)



<div class="col-12">
    <div class="pagination d-flex justify-content-center mt-5">
        <a href="#" class="rounded">&laquo;</a>
        <a href="#" class="active rounded">1</a>
        <a href="#" class="rounded">2</a>
        <a href="#" class="rounded">3</a>
        <a href="#" class="rounded">4</a>
        <a href="#" class="rounded">5</a>
        <a href="#" class="rounded">6</a>
        <a href="#" class="rounded">&raquo;</a>
    </div>
</div>
<!-- Fruits Shop End-->

CT288Book/Views/Book/ProductItem.cshtml
@model IEnumerable<CT288Book.ViewModels.BookVM>

<h3>Có <b>@Model.Count()</b> sản phẩm</h3>
@foreach (var item in Model)
{
    <div class="col-md-6 col-lg-6 col-xl-4">
        <div class="rounded position-relative fruite-item">
            <div class="fruite-img">
                <a asp-action="Detail" asp-controller="Book" asp-route-id="@item.MaHh">
                <img src="~/Hinh/HangHoa/@item.Hinh" class="img-fluid w-100 rounded-top" alt="@item.TenHH">
                </a>
            </div>
            <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">@item.TenLoai</div>
            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                <a asp-action="Detail" asp-controller="Book" asp-route-id="@item.MaHh">
                <h4>@item.TenHH</h4>
                </a>
                <p>@item.MoTaNgan</p>
                <div class="d-flex justify-content-between flex-lg-wrap">
                    <p class="text-dark fs-5 fw-bold mb-0">@item.DonGia</p>
                    <a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.MaHh" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Đưa vào giỏ</a>
                </div>
            </div>
        </div>
    </div>
}

CT288Book/Views/Book/Search.cshtml
@model IEnumerable<CT288Book.ViewModels.BookVM>
@{
    ViewData["Title"] = "Search";
    Layout = "_DanhSachBook";
}

<h1>Search</h1>
@await Html.PartialAsync("ProductItem", Model)